import { CommonLayout } from './common-layout';

export function Default() {
  return (
    <CommonLayout>
      <h2>Content</h2>
      <span>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec Lorem
        ipsum dolor sit amet, consectetur adipiscing elit. Donec Lorem ipsum
        dolor sit amet, consectetur adipiscing elit. Donec Lorem ipsum dolor sit
        amet, consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Donec
      </span>
    </CommonLayout>
  );
}
